# Generated by Django 5.1.4 on 2026-08-28 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_is_email_verified_customer_photo_url_and_more'),
        ('bookings', '0002_rename_booking_to_job'),
        ('drivers', '0001_initial'),
        ('geo', '0001_initial'),
        ('vehicles', '0003_customervehicle_confirmation_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='customer_tyre_size',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='customer_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='vehicles.customervehicle'),
        ),
        migrations.AddField(
            model_name='job',
            name='disclaimer_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='dispatch_rounds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='dispatch_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='job',
            name='en_route_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='eta_distance_metres',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='eta_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='eta_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='issue_label',
            field=models.CharField(blank=True, help_text='Label at the time of submission.', max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='location_accuracy_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location_source',
            field=models.CharField(choices=[('device', 'Native device location'), ('browser', 'Browser geolocation'), ('pin', 'Map pin'), ('staff', 'Entered by staff')], default='browser', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='looked_up_tyre_size',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='service_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='geo.servicearea'),
        ),
        migrations.AddField(
            model_name='job',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tyre_confirmation_path',
            field=models.CharField(blank=True, choices=[('confirmed', 'Path A — customer confirmed the looked-up specification'), ('overridden', 'Path B — customer supplied their own specification')], max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='tyre_corrected_on_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='tyre_correction_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobstatusevent',
            name='actor_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver'), ('staff', 'Staff'), ('system', 'System')], default='system', max_length=16),
        ),
        migrations.AddField(
            model_name='jobstatusevent',
            name='changed_by_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_changes', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='job',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='issue_type',
            field=models.CharField(help_text='A value from the configured issue list.', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='location_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('website', 'Customer website'), ('app', 'Customer app'), ('panel', 'Owner panel'), ('phone', 'Phone call')], default='website', max_length=16),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('dispatching', 'Dispatching'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('en_route', 'En route'), ('arrived', 'Arrived'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('unclaimed', 'Unclaimed')], db_index=True, default='submitted', max_length=16),
        ),
        migrations.AlterField(
            model_name='job',
            name='tyre_size',
            field=models.CharField(blank=True, help_text='The figure the van is loaded from.', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='jobstatusevent',
            name='changed_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='bookings_jo_status_767989_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['driver', 'status'], name='bookings_jo_driver__51adc1_idx'),
        ),
    ]
