# Generated by Django 5.1.4 on 2026-09-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_job_accepted_at_job_arrived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='damaged_positions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
