# Generated by Django 5.1.4 on 2026-08-28 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# 0002 renamed devicetoken.driver to customer. Postgres renames the column but keeps
# the index name, so on any database migrated before this point the FK index is still
# called ..._driver_id_... — exactly the name the AddField below generates. SQLite
# rebuilds the table on rename, so it is only Postgres that needs this out of the way.
_STALE = "notifications_devicetoken_driver_id_0c5b644f"
_FREED = "notifications_devicetoken_customer_id_0c5b644f"


def _rename_index(schema_editor, old, new):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(f"ALTER INDEX IF EXISTS {old} RENAME TO {new}")


def free_stale_driver_index_name(apps, schema_editor):
    _rename_index(schema_editor, _STALE, _FREED)


def restore_stale_driver_index_name(apps, schema_editor):
    _rename_index(schema_editor, _FREED, _STALE)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_is_email_verified_customer_photo_url_and_more'),
        ('drivers', '0001_initial'),
        ('notifications', '0002_rename_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            free_stale_driver_index_name,
            restore_stale_driver_index_name,
            elidable=True,
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='devicetoken',
            constraint=models.CheckConstraint(condition=models.Q(('customer__isnull', False), ('driver__isnull', False), ('staff__isnull', False), _connector='OR'), name='device_token_has_owner'),
        ),
    ]
