# Generated by Django 5.1.4 on 2026-08-28 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_job_accepted_at_job_arrived_at_and_more'),
        ('drivers', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('mode', models.CharField(choices=[('automatic', 'Automatic assignment'), ('selection', 'Driver selection')], max_length=16)),
                ('outcome', models.CharField(choices=[('pending', 'Awaiting a response'), ('accepted', 'A driver accepted'), ('rejected', 'Every driver rejected'), ('timed_out', 'Nobody responded in time'), ('no_candidates', 'No eligible driver was available'), ('superseded', 'Overtaken by a later round or a manual change')], db_index=True, default='pending', max_length=16)),
                ('radius_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timeout_seconds', models.PositiveIntegerField()),
                ('candidates_considered', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_attempts', to='bookings.job')),
                ('service_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_attempts', to='geo.servicearea')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='DispatchOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(help_text='1 is the best-ranked driver of the round.')),
                ('eta_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_metres', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn — taken by another driver'), ('timed_out', 'No response')], db_index=True, default='offered', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='dispatch.dispatchattempt')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_offers', to='drivers.driver')),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
        migrations.AddIndex(
            model_name='dispatchattempt',
            index=models.Index(fields=['outcome', 'expires_at'], name='dispatch_di_outcome_c7bf26_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchattempt',
            constraint=models.UniqueConstraint(fields=('job', 'round_number'), name='unique_dispatch_round'),
        ),
        migrations.AddIndex(
            model_name='dispatchoffer',
            index=models.Index(fields=['driver', 'state'], name='dispatch_di_driver__57d9ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchoffer',
            constraint=models.UniqueConstraint(fields=('attempt', 'driver'), name='unique_offer_per_attempt'),
        ),
    ]
