# Generated by Django 5.1.4 on 2026-09-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('auth', 'Sign-in and OTP'), ('sms', 'SMS'), ('email', 'Email'), ('push', 'Push notification'), ('job', 'Job'), ('dispatch', 'Dispatch'), ('billing', 'Billing'), ('stripe', 'Stripe'), ('settings', 'Settings'), ('driver', 'Driver'), ('staff', 'Staff'), ('system', 'System')], db_index=True, max_length=16)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=8)),
                ('message', models.CharField(max_length=255)),
                ('actor', models.CharField(blank=True, db_index=True, max_length=120)),
                ('subject_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('subject_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['category', '-created_at'], name='audit_audit_categor_27173c_idx'), models.Index(fields=['severity', '-created_at'], name='audit_audit_severit_17e6b2_idx')],
            },
        ),
    ]
