# Generated by Django 5.1.4 on 2026-09-15 19:08

import django.db.models.deletion
from django.db import migrations, models


def backfill_references(apps, schema_editor):
    """
    Give every invoice that predates the reference a unique one.

    Adding a unique column straight onto a populated table hands every existing
    row the same empty default and the index refuses to build — so the column
    arrives unconstrained, gets filled here, and is constrained afterwards.
    """
    import secrets
    import string

    Invoice = apps.get_model("billing", "Invoice")
    alphabet = string.ascii_uppercase + string.digits
    taken = set(
        Invoice.objects.exclude(reference="").values_list("reference", flat=True)
    )

    for invoice in Invoice.objects.filter(reference="").iterator():
        while True:
            candidate = "INV-" + "".join(secrets.choice(alphabet) for _ in range(6))
            if candidate not in taken:
                taken.add(candidate)
                break
        invoice.reference = candidate
        invoice.save(update_fields=["reference"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_staffuser_role'),
        ('billing', '0001_initial'),
        ('bookings', '0004_job_damaged_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_to_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hosted_invoice_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reference',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_mode',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='bookings.job'),
        ),
        migrations.RunPython(backfill_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='invoice',
            name='reference',
            field=models.CharField(blank=True, max_length=24, unique=True),
        ),
    ]
