# Generated by Django 5.1.4 on 2026-08-28 17:06

import apps.drivers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, upload_to=apps.drivers.models.driver_photo_path)),
                ('employment_reference', models.CharField(blank=True, help_text="The business's own staff reference.", max_length=64)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=16)),
                ('verification_note', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(db_index=True, default=False, help_text='Set by the driver app. Tracking runs only while true.')),
                ('went_online_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes, never shown to a customer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drivers', to=settings.AUTH_USER_MODEL)),
                ('service_areas', models.ManyToManyField(blank=True, related_name='drivers', to='geo.servicearea')),
            ],
            options={
                'ordering': ('name', 'phone'),
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('insurance', 'Insurance certificate'), ('licence', 'Driving licence'), ('mot', 'MOT certificate'), ('right_to_work', 'Right to work'), ('other', 'Other')], max_length=24)),
                ('file', models.FileField(upload_to=apps.drivers.models.document_path)),
                ('reference', models.CharField(blank=True, help_text='Policy or certificate number. Staff-only.', max_length=64)),
                ('expiry_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_warned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driver')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('driver', 'document_type', '-created_at'),
                'indexes': [models.Index(fields=['status', 'expiry_date'], name='drivers_dri_status_33d8cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('speed_kph', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heading_deg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='drivers.driver')),
            ],
            options={
                'ordering': ('-recorded_at',),
                'indexes': [models.Index(fields=['driver', '-recorded_at'], name='drivers_dri_driver__946657_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=16)),
                ('make', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('colour', models.CharField(blank=True, max_length=32)),
                ('year_of_manufacture', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='drivers.driver')),
            ],
            options={
                'ordering': ('-is_primary', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('driver', 'plate'), name='unique_driver_vehicle_plate')],
            },
        ),
    ]
