# Generated by Django 5.1.4 on 2026-09-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivervehicle',
            name='co2_emissions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivervehicle',
            name='dvla_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivervehicle',
            name='engine_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='cc', null=True),
        ),
        migrations.AddField(
            model_name='drivervehicle',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='drivervehicle',
            name='mot_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivervehicle',
            name='mot_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='drivervehicle',
            name='tax_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivervehicle',
            name='tax_status',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
