# Generated by Django 5.1.4 on 2026-09-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_is_email_verified_customer_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('shop_owner', 'Shop owner'), ('staff', 'Office')], default='staff', max_length=16),
        ),
    ]
