# Generated by Django 5.1.4 on 2026-08-26 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_links', to='accounts.driver')),
            ],
            options={
                'ordering': ('-is_primary', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=16, unique=True)),
                ('make', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('colour', models.CharField(blank=True, max_length=32)),
                ('fuel_type', models.CharField(blank=True, max_length=32)),
                ('engine_capacity', models.PositiveIntegerField(blank=True, help_text='cc', null=True)),
                ('year_of_manufacture', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('co2_emissions', models.PositiveIntegerField(blank=True, null=True)),
                ('tax_status', models.CharField(blank=True, max_length=32)),
                ('tax_due_date', models.DateField(blank=True, null=True)),
                ('mot_status', models.CharField(blank=True, max_length=32)),
                ('mot_expiry_date', models.DateField(blank=True, null=True)),
                ('tyre_size_front', models.CharField(blank=True, help_text='e.g. 205/55R16', max_length=32)),
                ('tyre_size_rear', models.CharField(blank=True, max_length=32)),
                ('tyre_load_index', models.CharField(blank=True, max_length=16)),
                ('tyre_speed_rating', models.CharField(blank=True, max_length=8)),
                ('tyre_pressure_front_psi', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tyre_pressure_rear_psi', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tyre_size_options', models.JSONField(blank=True, default=list, help_text='Alternative fitments when the trim is ambiguous.')),
                ('tyre_source', models.CharField(choices=[('api', 'Tyre data API'), ('driver', 'Confirmed by driver'), ('staff', 'Entered by staff'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('dvla_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('tyre_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('lookup_error', models.CharField(blank=True, max_length=255)),
                ('raw_dvla', models.JSONField(blank=True, default=dict)),
                ('raw_tyre', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drivers', models.ManyToManyField(related_name='vehicles', through='vehicles.DriverVehicle', to='accounts.driver')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='drivervehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_links', to='vehicles.vehicle'),
        ),
        migrations.AddConstraint(
            model_name='drivervehicle',
            constraint=models.UniqueConstraint(fields=('driver', 'vehicle'), name='unique_driver_vehicle'),
        ),
    ]
