# Generated by Django 5.1.4 on 2026-08-28 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_is_email_verified_customer_photo_url_and_more'),
        ('vehicles', '0002_rename_driver_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='confirmation_path',
            field=models.CharField(blank=True, choices=[('confirmed', 'Path A — customer confirmed the looked-up specification'), ('overridden', 'Path B — customer supplied their own specification')], max_length=16),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='customer_load_index',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='customer_speed_rating',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='customer_tyre_size',
            field=models.CharField(blank=True, help_text='What the customer entered instead, on path B.', max_length=32),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='disclaimer_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Path B only: when the responsibility notice was acknowledged.', null=True),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='looked_up_tyre_size',
            field=models.CharField(blank=True, help_text='What the lookup returned at the moment of confirmation.', max_length=32),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customervehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_links', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tyre_source',
            field=models.CharField(choices=[('api', 'Tyre data API'), ('customer', 'Confirmed by customer'), ('staff', 'Entered by staff'), ('driver', 'Corrected by driver on site'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='customervehicle',
            constraint=models.UniqueConstraint(fields=('customer', 'vehicle'), name='unique_customer_vehicle'),
        ),
    ]
