# Generated by Django 5.1.4 on 2026-08-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('boundary', models.JSONField(help_text='GeoJSON Polygon or MultiPolygon, [longitude, latitude] order.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.SmallIntegerField(default=0, help_text='Higher wins where areas overlap.')),
                ('dispatch_overrides', models.JSONField(blank=True, default=dict, help_text='Setting keys from the dispatch group that differ inside this area.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-priority', 'name'),
            },
        ),
    ]
